In [7]:
# coding:utf-8

In [8]:
'''
from urllib2 import urlopen
from contextlib import closing
url = "http://aima.cs.berkeley.edu/data/iris.csv"
with closing(urlopen(url)) as u, open("iris.csv", "w") as f:
 f.write(u.read())
'''

'\nfrom urllib2 import urlopen\nfrom contextlib import closing\nurl = "http://aima.cs.berkeley.edu/data/iris.csv"\nwith closing(urlopen(url)) as u, open("iris.csv", "w") as f:\n f.write(u.read())\n'

In [9]:
import os 
os.getcwd()

'/Users/apple'

In [10]:
os.listdir('/Users/apple')

['.anaconda',
 '.android',
 '.bash_history',
 '.bash_profile',
 '.bash_sessions',
 '.CFUserTextEncoding',
 '.condarc',
 '.config',
 '.continuum',
 '.cups',
 '.DS_Store',
 '.eclipse',
 '.gitconfig',
 '.ipynb_checkpoints',
 '.ipython',
 '.jssc',
 '.jupyter',
 '.oracle_jre_usage',
 '.p2',
 '.Rapp.history',
 '.Rhistory',
 '.rstudio-desktop',
 '.ssh',
 '.subversion',
 '.tooling',
 '.Trash',
 '.viminfo',
 '.wget-hsts',
 '.zenmap',
 '123 .html',
 'anaconda',
 'AnacondaProjects',
 'Applications',
 'buttonhelloworld',
 'bwgex',
 'Desktop',
 'Documents',
 'Downloads',
 'GATTinBluetooth',
 'gps.json',
 'gps.json.1',
 'gps.json.2',
 'gps.json.3',
 'gps2.json',
 'IOT_course',
 'iris.csv',
 'jsbin.fihozihere.1.html',
 'Library',
 'LuaNode',
 'Movies',
 'Music',
 'nodemcu-prebuilt-toolchains',
 'Pictures',
 'plot_lda.ipynb',
 'Public',
 'test.html',
 'test.py',
 'Untitled.ipynb',
 'untitled.txt',
 'Untitled1.ipynb',
 'VirtualBox VMs']

In [11]:
from numpy import genfromtxt, zeros
# read the first 4 columns
data = genfromtxt("iris.csv",delimiter=",",usecols=(0,1,2,3))
# read the fifth column
# this fifth column is the label (or target)
target = genfromtxt("iris.csv",delimiter=",",usecols=(4),dtype=str)


In [12]:
print data.shape
print target.shape

(150, 4)
(150,)


In [13]:
print set(target)

set(['setosa', 'versicolor', 'virginica'])


In [14]:
t = zeros(len(target))
t[target == "setosa"] = 1
t[target == "versicolor"] = 2
t[target == "virginica"] = 3


In [15]:
# import 你的演算法
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis


In [16]:
# 建構你的訓練模型並且餵入資料集
LinearDiscrimnat_clf = LinearDiscriminantAnalysis(solver='lsqr', shrinkage='auto').fit(data, t)


In [17]:
print LinearDiscrimnat_clf.predict(data[0])


[ 1.]


/Users/apple/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [18]:
print t[0]


1.0


In [19]:
from sklearn import cross_validation
train, test, t_train, t_test = cross_validation.train_test_split(data, t,test_size=0.4, random_state=0)


In [20]:
LinearDiscrimnat_clf.fit(train,t_train) # train
print LinearDiscrimnat_clf.score(test,t_test) # test


0.933333333333


In [21]:
from sklearn.metrics import confusion_matrix
print confusion_matrix(LinearDiscrimnat_clf.predict(test),t_test)


[[16  0  0]
 [ 0 23  4]
 [ 0  0 17]]


In [22]:
from sklearn.metrics import classification_report
print classification_report(LinearDiscrimnat_clf.predict(test), t_test,target_names=["setosa", "versicolor", "virginica"])


             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        16
 versicolor       1.00      0.85      0.92        27
  virginica       0.81      1.00      0.89        17

avg / total       0.95      0.93      0.93        60



In [23]:
from sklearn.cross_validation import cross_val_score
# cross validation with 6 iterations
scores = cross_val_score(LinearDiscrimnat_clf, data, t, cv=6)
print scores

[ 1.          1.          0.95833333  0.91666667  1.          1.        ]


In [24]:
from numpy import mean 
print mean(scores)

0.979166666667
